Update for running soak repo instead of executable and use chainlink ecr images

diff --git a/charts/remote-test-runner/templates/test-runner-config-map.yaml b/charts/remote-test-runner/templates/test-runner-config-map.yaml
--- a/charts/remote-test-runner/templates/test-runner-config-map.yaml
+++ b/charts/remote-test-runner/templates/test-runner-config-map.yaml
@@ -10,33 +10,46 @@ data:
     {{ .Values.remote_test_runner.config_file_contents }}
   init.sh: |
     #!/bin/sh
+    set -x
+
+    # Steps to use this
+    # 1. Push up a test repo or directory as src to /root/src
+    # 2. Push up or create an empty file at /root/start.txt
+    # Once the start.txt file has been created the test will begin
+
+    TAR_FILE=/root/ztarrepo.tar.gz
+    REPO_SRC=/root/src
     
     echo "Adding private Helm repos"
     helm repo add chainlink-qa https://raw.githubusercontent.com/smartcontractkit/qa-charts/gh-pages/
 
-    echo "Waiting for $TEST_FILE to start being copied"
-    until [ -f $TEST_FILE ]
+    echo "Installing ginkgo"
+    go install github.com/onsi/ginkgo/v2/ginkgo@v"{{ .Values.remote_test_runner.ginkgo_version }}"
+
+    echo "Waiting for $START_FILE to start being copied"
+    until [ -f $START_FILE ]
     do
       sleep 1
     done
-    echo "Found $TEST_FILE"
+    echo "Found $START_FILE"
 
-    CURRENT_FILE_SIZE=$(stat -c%s "$TEST_FILE")
-    until [ "$CURRENT_FILE_SIZE" -eq "$TEST_FILE_SIZE" ]
-    do
-      CURRENT_FILE_SIZE=$(stat -c%s "$TEST_FILE")
-      echo "Copied $CURRENT_FILE_SIZE/$TEST_FILE_SIZE bytes"
-      sleep 1
-    done
+    echo "The start file has been created, check if the test repo is present."
+    if [ ! -f "${TAR_FILE}" ]; then
+      echo "Test repo was not present in ${REPO_SRC}"
+      exit 1
+    fi
 
-    chmod +x $TEST_FILE
-    echo "File details"
-    stat $TEST_FILE
-    echo "-----------"
-    file $TEST_FILE
-    echo "-----------"
-    ldd $TEST_FILE
+    cd /root/
+    mkdir ${REPO_SRC}
+    tar -zxf ztarrepo.tar.gz -C ${REPO_SRC}
 
-    echo "Copied $TEST_FILE Successfully! Running test..."
-    echo "Connecting to namespace $ENV_NAMESPACE"
-    ENV_NAMESPACE=$ENV_NAMESPACE $TEST_FILE --ginkgo.timeout=0 --ginkgo.v --ginkgo.focus {{ .Values.remote_test_runner.test_name }}
+    echo "Running test..."
+    echo "Connecting to namespace {{ .Values.remote_test_runner.env_namespace }}"
+    cd "${REPO_SRC}/usr/src/" || echo "Failed to cd into ${REPO_SRC}/usr/src/ before running test"
+    CGO_ENABLED=1 \
+    ENV_NAMESPACE={{ .Values.remote_test_runner.env_namespace }} \
+    ginkgo \
+    --timeout=0 \
+    -v -r \
+    --focus {{ .Values.remote_test_runner.focus }} \
+    {{ .Values.remote_test_runner.test_dir }}
